
name: Test and Notify

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest discover tests

  notify:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_message: "Tests passed on main branch. :tada:"
          slack_channel: "#test-notifications"
          slack_username: "GitHub Actions"
          slack_icon: ":github:"
          slack_color: "good"

